version: '3'
services:
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - db
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 54321:5432
    
#   proxy:
#     build:
#       context: .
#       dockerfile: ProxyDockerfile
#     ports:
#       - 9999:80
#     depends_on: 
#       - backend
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
      - "6379:6379"

volumes:
  db-data:

networks:
  app-tier:
    driver: bridge